aws_access_key = "ENTER YOUR ACCESS KEY HERE"
aws_secret_key = "ENTER YOUR SECRET KEY HERE"
keyName = "ENTER KEY NAME HERE"
keyLocation = "ENTER YOUR LOCAL KEY LOCATION HERE"
ami_id = "ami-08df646e18b182346"
machine_type = "t2.micro"
instance_region = "ap-south-1"
subnetID = "subnet-03f58a4f"
